### PR TITLE
Reactor 3.1 support

### PR DESCRIPTION
**Pull request by dbacinski**
`Cancellation` interface was replaced with `Disposable` in Reactor 3.1

Not sure if it is proper fix.

### CODE REVIEW

**Comment by JakeWharton** [comment]
This looks good other than reformatting the indent and code style. I'll clean it up this weekend.

**Comment by dbacinski** [comment]
Meanwhile I am using build with my fix and it is working correctly.
https://jitpack.io/#dbacinski/retrofit2-reactor-adapter/0465eed5c3

**Comment by dbacinski** [comment]
After update of Reactor to 3.1.0 M3 all tests related to Backpressure are failing.

I have debugged it and in class CallSinkConsumer:

`sink.onDispose(call::cancel)` is called before ` response = call.execute();` and we are getting IOException: Cancelled from OKHttp.

I am not sure how to fix those tests...

**Comment by JakeWharton** [comment]
Thanks. I was waiting for 3.1's final release before merging the update. I
can try to take a look later in the week though.

**Comment by dbacinski** [comment]
Final release will be next week https://github.com/reactor/reactor-core/milestone/20 so no need to hurry:)

**Comment by zlangbert** [comment]
Reactor 3.1 has been released for a little while now, any chance this can be merged? Thanks!

**Pull request closed without merging**
